### ISSUE TITLE
guile-dbi not building.

### ISSUE THREAD

**Issue by bret-walda** [opencog/guile-dbi#10]
So i wanted to build guile-dbi from the repo so i cloned it and tried building it but I had some problems with a macro named 
`AC_LIB_LINKFLAGS_FROM_LIBS`. The error was that it said this was a possibly an undefined macro so looking inside `guile.m4` i found the macro, it stated that it needed the `lib-link.m4` from `gnulib/m4/lib-link.m4` so i cloned the repo and at first i just pointed the `ACLOCAL_PATH` to `gnulib/m4/`. This time the building worked and it finished fine and then the reset of the build went fine i configured it and installed it in `/usr` and the `guile-dbd-postgresql` which didn't give me any errors and installed easily.
Now when i did `(use-modules (dbi dbi))` inside guile it gave me this error:

`guile: symbol lookup error: /usr/lib/libguile-dbi.so: undefined symbol: lt_dlinit
`

and i haven't been able to progress past this error and i have tried everything from building again to using the `gnulib-tool` to import the `lib-link.m4` and adjusting as the instructions wanted me to alter some files. Which again built fine but i was then confronted with the same error.
I tried `autoreconf -vif` which gave me that configure.ac was not using `Gettext` and `gtk3doc` and one other module, I don't know if this is relevant but i wanted to mention it briefly and also the gnulib-tool had instructions to invoke `gl_EARLY` at a precise point but not `gl_INIT` so i put it just before `AC_OUTPUT`. I don't know if i am overdoing this or simply missing a dependency that could easily fix this. 

I am trying to build it on Arch Linux.
I also used ldconfig to update the cache.

What can i do to fix this error.

**Comment by linas** [comment]
You bring up multiple issues here. Regarding autotools macros, the first problem might be solvable by installing the `autoconf-archive` package (not sure what it's called on Arch, should be something like that.)

My guess is that doing this will solve all the other problems.

Also, which version of guile are you using?  I strongly recommend guile-3.0 and not guile-2.2

The error about `/usr/lib/libguile-dbi.so` is weird, because that is not where this file is usually installed. Are you sure that is not some old leftoever  from some old version or old attempt?

**Comment by linas** [comment]
Oh. Hah. To solve the `undefined symbol: lt_dlinit ` problem, you also need to link to `libltdl`   and yes, the code here should have done this automatically, and I don't know why it did not. Investigating.

**Comment by bret-walda** [comment]
> You bring up multiple issues here. Regarding autotools macros, the first problem might be solvable by installing the `autoconf-archive` package (not sure what it's called on Arch, should be something like that.)
> 
> My guess is that doing this will solve all the other problems.
> 
> Also, which version of guile are you using? I strongly recommend guile-3.0 and not guile-2.2
> 
> The error about `/usr/lib/libguile-dbi.so` is weird, because that is not where this file is usually installed. Are you sure that is not some old leftoever from some old version or old attempt?

Yes, installing autoconf-archive was the first thing i did when I realized I didn't have it but sadly it didn't fix the issue. 

I am using guile 3.0 

The reason  /usr/lib/libguile-dbi.so is installed there because I used --prefix=/usr because that is where guile is installed. I thought maybe installing it in the same dir guile was would fix the problem but it didn't. At first the lib was installed at /usr/local/lib. I only tried this because guile-json worked when I installed it in the same dir as guile. I thought it was worth a try.

**Comment by linas** [comment]
Ah, OK, yes, that sounds good. I now see that on my system, I have kind-of the same error:
```
ldd -r /usr/local/lib/libguile-dbi.so.2.0.9
...
undefined symbol: lt_dlopenext	(/usr/local/lib/libguile-dbi.so.2.0.9)
undefined symbol: lt_dlclose	(/usr/local/lib/libguile-dbi.so.2.0.9)
undefined symbol: lt_dlerror	(/usr/local/lib/libguile-dbi.so.2.0.9)
undefined symbol: lt_dlsym	(/usr/local/lib/libguile-dbi.so.2.0.9)
undefined symbol: lt_dlinit	(/usr/local/lib/libguile-dbi.so.2.0.9)
undefined symbol: lt_dlsetsearchpath	(/usr/local/lib/libguile-dbi.so.2.0.9)
```
and this can be solved by linking to `libltdl` and so I'm not sure why that didn't happen automatically.  Looking ito that now.

**Comment by bret-walda** [comment]
> Ah, OK, yes, that sounds good. I now see that on my system, I have kind-of the same error:
> 
> ```
> ldd -r /usr/local/lib/libguile-dbi.so.2.0.9
> ...
> undefined symbol: lt_dlopenext	(/usr/local/lib/libguile-dbi.so.2.0.9)
> undefined symbol: lt_dlclose	(/usr/local/lib/libguile-dbi.so.2.0.9)
> undefined symbol: lt_dlerror	(/usr/local/lib/libguile-dbi.so.2.0.9)
> undefined symbol: lt_dlsym	(/usr/local/lib/libguile-dbi.so.2.0.9)
> undefined symbol: lt_dlinit	(/usr/local/lib/libguile-dbi.so.2.0.9)
> undefined symbol: lt_dlsetsearchpath	(/usr/local/lib/libguile-dbi.so.2.0.9)
> ```
> 
> and this can be solved by linking to `libltdl` and so I'm not sure why that didn't happen automatically. Looking ito that now.

Thanks man I really appreciate the help. But can you tell me where should I link it manually I am kind of new to this so a bit confused because the autotools and configure scripts don't give you that much freedom to work with at least in my opinion so I am a bit confused at what stage should I link and how can I do it. 
Thanks again for the help.

**Comment by linas** [comment]
Beats me. Trying to figure that out now.

**Comment by linas** [comment]
Did you get this error:
```
checking for guile-3.0... yes
../configure: line 20324: syntax error near unexpected token `3.0'
../configure: line 20324: `GUILE_PKG(3.0)'
```
Because in the past, it worked for me, but today, I get this error, so I am confused...

**Comment by bret-walda** [comment]
> Beats me. Trying to figure that out now.

Bro if it beats you what chance do I have.😭😭

**Comment by bret-walda** [comment]
> Did you get this error:
> 
> ```
> checking for guile-3.0... yes
> ../configure: line 20324: syntax error near unexpected token `3.0'
> ../configure: line 20324: `GUILE_PKG(3.0)'
> ```
> 
> Because in the past, it worked for me, but today, I get this error, so I am confused...

No I didn't get this error.

**Comment by linas** [comment]
I just merged pull req #11 which fixes this issue.   Please `git pull` and try again.

This means running `./autogen.sh --no-configure` again (maybe setting the  `ACLOCAL_PATH` although I am surprised that this was needed.

However,, do be careful to clean out the build dir i.e. `rm -r build` and then recreate it. When I failed to do this, some kind of left-over grunge kept ruining my build, and it was very confusing :-(

I'm closing this issue, cause I think its now fixed.  Open a new issue if there are bugs

**Comment by linas** [comment]
Seems that a prereq is to install the `gettext` package. I'm modifying the README now

**Comment by bret-walda** [comment]
> Seems that a prereq is to install the `gettext` package. I'm modifying the README now

Just to make everything clear even though it says that the lib-link.m4 is provided by gettext it didn't fix this for me. Because i had gettext installed and running autoreconf would always tell me that configure.ac was not using gettext. But you should still install gettext just in case. what did fix it for me was that i cloned the gnulib repo and pointed ACLOCAL_PATH to gnulib/m4 or import it using gnulib-tool both worked for me. I just wanted to say this here just in case installing packages doesn't fix the problem for someone else like it didn't for me.

**Comment by bret-walda** [comment]
But yeah the problem overall is fixed. Thanks linas, very cool.

**Comment by linas** [comment]
FYI, I also bumped the version number to 3.0.0 from 2.1.9. Nothing actually changes; this is to avoid user confusion about guile-3.0 vs guile-2.2 and yes, its silly, but human psychology is kind of more important than strict numbering policy.

**Comment by bret-walda** [comment]
> FYI, I also bumped the version number to 3.0.0 from 2.1.9. Nothing actually changes; this is to avoid user confusion about guile-3.0 vs guile-2.2 and yes, its silly, but human psychology is kind of more important than strict numbering policy.

Yeah no problem I understand. Have a great day.
